#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Pfazzi\DxMetrics\Analyze;
use Pfazzi\DxMetrics\CodeownersDrift;
use Pfazzi\DxMetrics\CodeownersSuggest;
use Pfazzi\DxMetrics\CouplingTrend;
use Pfazzi\DxMetrics\Init;
use Pfazzi\DxMetrics\OwnershipGaps;
use Pfazzi\DxMetrics\OwnershipHotspots;
use Pfazzi\DxMetrics\OwnershipTrend;
use Pfazzi\DxMetrics\SharedOwnership;
use Pfazzi\DxMetrics\SharedOwnershipInit;
use Pfazzi\DxMetrics\TerritoryMap;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Init());
$application->add(new Analyze());
$application->add(new SharedOwnership());
$application->add(new SharedOwnershipInit());
$application->add(new OwnershipHotspots());
$application->add(new OwnershipGaps());
$application->add(new TerritoryMap());
$application->add(new CouplingTrend());
$application->add(new OwnershipTrend());
$application->add(new CodeownersSuggest());
$application->add(new CodeownersDrift());

$application->run();